"use client";

import * as React from "react";
import { motion } from "framer-motion";
import { KodandLogo } from "@/components/kodand-logo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  ArrowLeft,
  BarChart3,
  Search,
  TrendingUp,
  Loader2,
  Tags,
  Globe,
  Eye,
  Copy,
  Check,
  Code,
  Facebook,
  Twitter,
  Linkedin,
  AlertTriangle,
  CheckCircle2,
} from "lucide-react";
import Link from "next/link";
import { AppFooter } from "@/components/layout/app-footer";

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = React.useState(false);
  return (
    <button type="button" onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }} className="p-1 rounded hover:bg-emerald-500/10 text-muted-foreground hover:text-emerald-300 transition-colors" title="Copy">
      {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
    </button>
  );
}

function CopyBlock({ label, value }: { label: string; value: string }) {
  return (
    <div className="space-y-1">
      <div className="text-[10px] text-muted-foreground font-mono uppercase tracking-wider">{label}</div>
      <div className="p-2.5 rounded-lg border border-emerald-500/15 bg-emerald-500/5 text-sm flex items-center justify-between gap-2">
        <span className="flex-1 min-w-0 break-words">{value}</span>
        <CopyButton text={value} />
      </div>
    </div>
  );
}

export default function MarketingPage() {
  const [url, setUrl] = React.useState("");
  const [keyword, setKeyword] = React.useState("");
  const [loading, setLoading] = React.useState(false);
  const [metaTags, setMetaTags] = React.useState<any>(null);
  const [error, setError] = React.useState<string | null>(null);

  const generateMeta = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!url.trim()) return;
    setLoading(true);
    setError(null);
    setMetaTags(null);
    try {
      const res = await fetch("/api/marketing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "meta-generator", url: url.trim(), keyword: keyword.trim() || undefined }),
      });
      const data = await res.json();
      if (data.error) { setError(data.error); } else { setMetaTags(data.metaTags); }
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  };

  const buildHtmlSnippet = () => {
    if (!metaTags) return "";
    return `<!-- SEO Meta Tags - Generated by KODAND -->
<title>${metaTags.title}</title>
<meta name="description" content="${metaTags.description}" />
<meta name="keywords" content="${(metaTags.keywords || []).join(", ")}" />
<link rel="canonical" href="${metaTags.canonicalUrl}" />

<!-- Open Graph -->
<meta property="og:title" content="${metaTags.ogTitle}" />
<meta property="og:description" content="${metaTags.ogDescription}" />
<meta property="og:url" content="${metaTags.canonicalUrl}" />
<meta property="og:type" content="website" />

<!-- Twitter Card -->
<meta name="twitter:card" content="${metaTags.twitterCard}" />
<meta name="twitter:title" content="${metaTags.twitterTitle}" />
<meta name="twitter:description" content="${metaTags.twitterDescription}" />

<!-- Structured Data -->
<script type="application/ld+json">
${JSON.stringify(metaTags.structuredData, null, 2)}
</script>`;
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="sticky top-0 z-30 border-b border-emerald-500/15 bg-background/85 backdrop-blur">
        <div className="mx-auto max-w-[1600px] px-4 h-14 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <Link href="/" className="flex items-center gap-2 text-emerald-300 hover:text-emerald-200 text-sm">
              <ArrowLeft className="size-4" />
              <span className="hidden sm:inline">Dashboard</span>
            </Link>
            <div className="w-px h-6 bg-emerald-500/20" />
            <KodandLogo size="md" />
          </div>
          <div className="flex items-center gap-2">
            <Link href="/keywords">
              <Button variant="ghost" size="sm" className="text-xs text-muted-foreground hover:text-emerald-300">
                <Search className="size-3.5 mr-1" /> Keywords
              </Button>
            </Link>
            <Link href="/backlinks">
              <Button variant="ghost" size="sm" className="text-xs text-muted-foreground hover:text-emerald-300">
                <TrendingUp className="size-3.5 mr-1" /> Backlinks
              </Button>
            </Link>
          </div>
        </div>
      </header>

      <main className="flex-1 mx-auto w-full max-w-6xl px-4 py-8">
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
          <div className="text-center mb-8">
            <h1 className="text-2xl sm:text-3xl font-bold text-foreground flex items-center justify-center gap-3 mb-2">
              <BarChart3 className="size-7 text-amber-400" />
              Digital Marketing Tools
            </h1>
            <p className="text-muted-foreground text-sm max-w-xl mx-auto">
              Generate optimized meta tags, preview social cards, and get actionable SEO recommendations.
            </p>
          </div>

          <Tabs defaultValue="meta" className="space-y-6">
            <TabsList className="bg-card/60 border border-emerald-500/20 mx-auto flex w-fit">
              <TabsTrigger value="meta" className="text-xs data-[state=active]:bg-emerald-500/20 data-[state=active]:text-emerald-300">
                <Tags className="size-3.5 mr-1" /> Meta Generator
              </TabsTrigger>
              <TabsTrigger value="social" className="text-xs data-[state=active]:bg-emerald-500/20 data-[state=active]:text-emerald-300">
                <Eye className="size-3.5 mr-1" /> Social Preview
              </TabsTrigger>
              <TabsTrigger value="code" className="text-xs data-[state=active]:bg-emerald-500/20 data-[state=active]:text-emerald-300">
                <Code className="size-3.5 mr-1" /> HTML Code
              </TabsTrigger>
            </TabsList>

            <TabsContent value="meta">
              <form onSubmit={generateMeta} className="max-w-2xl mx-auto space-y-3 mb-6">
                <div className="flex gap-2">
                  <div className="relative flex-1">
                    <Globe className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-amber-400" />
                    <Input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="Enter page URL (e.g. https://example.com/about)" className="pl-10 h-11 bg-card/80 border-amber-500/30 focus-visible:border-amber-400" />
                  </div>
                </div>
                <div className="flex gap-2">
                  <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-amber-300/50" />
                    <Input value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Target keyword (optional)" className="pl-10 h-11 bg-card/80 border-amber-500/20" />
                  </div>
                  <Button type="submit" disabled={loading} className="h-11 px-6 bg-gradient-to-r from-amber-600 to-yellow-500 text-white border border-amber-400/40">
                    {loading ? <Loader2 className="size-4 animate-spin" /> : <Tags className="size-4" />}
                    <span className="ml-2">Generate</span>
                  </Button>
                </div>
              </form>

              {error && <div className="max-w-2xl mx-auto mb-4 p-3 rounded-lg border border-rose-500/40 bg-rose-500/10 text-rose-200 text-sm">{error}</div>}

              {metaTags && (
                <div className="max-w-3xl mx-auto space-y-4">
                  <CopyBlock label="Title Tag" value={metaTags.title} />
                  <CopyBlock label="Meta Description" value={metaTags.description} />
                  <CopyBlock label="OG Title" value={metaTags.ogTitle} />
                  <CopyBlock label="OG Description" value={metaTags.ogDescription} />
                  <CopyBlock label="Twitter Title" value={metaTags.twitterTitle} />
                  <CopyBlock label="Twitter Description" value={metaTags.twitterDescription} />
                  {metaTags.keywords && (
                    <div>
                      <div className="text-[10px] text-muted-foreground font-mono uppercase tracking-wider mb-1">Target Keywords</div>
                      <div className="flex flex-wrap gap-1.5">
                        {metaTags.keywords.map((kw: string, i: number) => (
                          <Badge key={i} variant="outline" className="text-[11px] border-emerald-500/25 text-emerald-200">{kw}</Badge>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </TabsContent>

            <TabsContent value="social">
              {metaTags ? (
                <div className="max-w-2xl mx-auto space-y-6">
                  {/* Facebook Preview */}
                  <Card className="bg-card/60 border-blue-500/20 overflow-hidden">
                    <div className="px-4 py-2 border-b border-blue-500/15 flex items-center gap-2">
                      <div className="size-5 rounded bg-blue-500 flex items-center justify-center text-white text-[10px] font-bold">f</div>
                      <span className="text-xs font-semibold text-blue-300">Facebook</span>
                    </div>
                    <CardContent className="p-4">
                      <div className="border border-gray-700 rounded-lg overflow-hidden">
                        <div className="h-32 bg-gray-800 flex items-center justify-center text-muted-foreground text-xs">Image Preview</div>
                        <div className="p-3 bg-card/80">
                          <div className="text-[10px] text-muted-foreground uppercase">{url}</div>
                          <div className="text-sm font-semibold text-foreground mt-0.5">{metaTags.ogTitle}</div>
                          <div className="text-xs text-muted-foreground mt-0.5 line-clamp-2">{metaTags.ogDescription}</div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  {/* Twitter Preview */}
                  <Card className="bg-card/60 border-sky-500/20 overflow-hidden">
                    <div className="px-4 py-2 border-b border-sky-500/15 flex items-center gap-2">
                      <div className="size-5 rounded bg-sky-500 flex items-center justify-center text-white text-[10px] font-bold">𝕏</div>
                      <span className="text-xs font-semibold text-sky-300">Twitter / X</span>
                    </div>
                    <CardContent className="p-4">
                      <div className="border border-gray-700 rounded-2xl overflow-hidden">
                        <div className="h-32 bg-gray-800 flex items-center justify-center text-muted-foreground text-xs">Image Preview</div>
                        <div className="p-3 bg-card/80">
                          <div className="text-sm font-semibold text-foreground">{metaTags.twitterTitle}</div>
                          <div className="text-xs text-muted-foreground mt-0.5 line-clamp-2">{metaTags.twitterDescription}</div>
                          <div className="text-[10px] text-muted-foreground mt-1">{url}</div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              ) : (
                <div className="text-center text-muted-foreground text-sm py-12">
                  Generate meta tags first to preview social cards
                </div>
              )}
            </TabsContent>

            <TabsContent value="code">
              {metaTags ? (
                <div className="max-w-3xl mx-auto">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs text-muted-foreground font-mono uppercase">Copy this into your &lt;head&gt;</span>
                    <CopyButton text={buildHtmlSnippet()} />
                  </div>
                  <pre className="p-4 rounded-lg border border-emerald-500/15 bg-emerald-500/5 text-xs font-mono text-emerald-200 overflow-x-auto whitespace-pre-wrap">
                    {buildHtmlSnippet()}
                  </pre>
                </div>
              ) : (
                <div className="text-center text-muted-foreground text-sm py-12">
                  Generate meta tags first to see the HTML code
                </div>
              )}
            </TabsContent>
          </Tabs>
        </motion.div>
      </main>
      <AppFooter />
    </div>
  );
}
